### ISSUE TITLE
stuck when going 'up' too much

### ISSUE THREAD

**Issue by seghers** [kashifo/android-folder-picker-library#2]
Thank you for this library.

When going up above '/storage/emulated/0/' the picker behaves in strange ways.
It's probably related to the way android created these 'virtual paths'

possible solution: add an extra to the intend (max_height, top_reach)
eg. /storage/emulated/0/ > /storage/emulated/0/*
eg. /storage/emulated/0/DCIM/ > /storage/emulated/0/DCIM/*
eg. /storage/emulated/0/DCIM/Camera > /storage/emulated/0/DCIM/Camera*

Testdevice: Huawei p9 lite

**Comment by kashifo** [comment]
It's my pleasure, it'll be fixed in the next version Insha Allah. 
Thank you very much for your feedback,

**Comment by wangxuchao** [comment]
Thank you for this library.

I avoid this bug by judging whether it contains files.

`public void goBack(View v) {
    	
        if( location!=null && !location.equals("") && !location.equals("/") ) {
            int start = location.lastIndexOf('/');
            String newLocation = location.substring(0, start);
            // fix stuck when going 'up' too much
            File folder = new File(newLocation);
            if( !folder.isDirectory() )
                return;
            File[] files = folder.listFiles();
    		if (files == null) {
    			return;
    		}
    		
            location = newLocation;
            loadLists(location);
        }

    }`

**Comment by kashifo** [comment]
Thanks for posting this issue, it has been resolved in the recent commit b73b1757387e312ad2fd2a24f41f75c8c0981fe7
