### ISSUE TITLE
How to be Internationalization for its UI?

### ISSUE THREAD

**Issue by KakiLiang** [kashifo/android-folder-picker-library#5]
Such as Chinesization. Thanks!

**Comment by kashifo** [comment]
Good question, If you want to localize this library

1. Download a zip copy
2. Add the folder 'folderpicker' as module to your project where you want to use.
3. Translate the strings.xml in you language of you choice

**Comment by KakiLiang** [comment]
OK. Thankyou

**Comment by KakiLiang** [comment]
OK. Thankyou

**Comment by KakiLiang** [comment]
OK. Thankyou

**Comment by KakiLiang** [comment]
OK. Thankyou

**Comment by KakiLiang** [comment]
OK. Thankyou

**Comment by kashifo** [comment]
My Pleasure @KakiLiang
