### ISSUE TITLE
internal storage / SD Card

### ISSUE THREAD

**Issue by KakiLiang** [kashifo/android-folder-picker-library#6]
How to let the end user choose the internal storage or SD Card?

**Comment by kashifo** [comment]
As of now it can be achieved by passing the path of internal or external storage.

**Comment by KakiLiang** [comment]
That means, its default path is the sd card's root folder?
if want to change it, just like as the below code? Thanks!
//To begin from a selected folder instead of sd card's root folder. Example : Pictures directory
       intent.putExtra("location", Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).getAbsolutePath());
