### ISSUE TITLE
Incorrect requestCode

### ISSUE THREAD

**Issue by nickfl** [kashifo/android-folder-picker-library#7]
By some reason _onActivityResult_ gets incorrect _requestCode_ (65869) instead of passed to _startActivityForResult_ (333), _resultCode_ is OK (-1).
The only difference with the example is that I called 'startActivityForResult' from the **Fragment**.
BTW, related 'onActivityResult' is called with **correct** "data" in returned 'intent'.

P.S. never mind, my bad, I should've call _**getActivity()**.startActivityForResult_...

**Comment by kashifo** [comment]
I guess you got it that you've to deal differently with activities and fragments.

**Comment by kashifo** [comment]
Thanks for using and tinkering with this lib.

**Comment by 25Shubham96** [comment]
i am stuck with the same problem and tried with using getActivity.startActivityForResult

not able to see the content of root directory
